version: '3' 
 
volumes: 
  postgres_data:
  static_volumes: 
 
services:
 
  db: 
    image: postgres:12.4 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    env_file: 
      - ./.env
 
  web: 
  # build: .
    image: ilyukevich/yamdb:v1 
    restart: always 
       ports: 
      - "8000:8000"  
    depends_on: 
      - db 
    - static_volumes:/code/static
    env_file: 
      - ./.env
 
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/code/static
    restart: always
    ports: 
      - "1337:80"
    depends_on:
      - web
