version: '3' 
 
volumes: 
  postgres_data:
  services: 
 
services:
 
  db: 
    image: postgres:12.4 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    env_file: 
      - ./.env
 
  web:
    image: ilyukevich/yamdb:v1 
    restart: always 
    depends_on: 
      - db 
    env_file: 
      - ./.env
 
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./static:/static
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/etc/nginx/conf.d/
      - ./media:/media
    ports: 
      - "80:80"
    depends_on:
      - web
