version: '3'

volumes:
  postgres_data:
  static_volumes:
  nginx_volumes:

services:
  db:
    image: postgres:12.4 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    env_file:
      - ./.env
  web:
    image: ilyukevich/workflow:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - static_volumes:/var/nginx/static/
      - nginx_volumes:/etc/nginx/conf.d/
    depends_on:
      - web
